n = 16
(
    GET_LANG,
    GET_NAME,
    GET_CONTACT,
    CLICK_LANG,
    ALL_SETTINGS,
    LANG_SETTINGS,
    NAME_SETTINGS,
    PHONE_SETTINGS,
    GET_BRAND_NAME,
    GET_MODEL_NAME,
    GET_REGION,
    GET_FEEDBACK_MESSAGE,
    AUTH_PASSPORT,
    AUTH_CODE,
    MY_PROFILE,
    INSTALLMENT,
) = range(0, n)
